spring:
  application:
    name: pedidos-ms

  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: postgres
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
    queue: ${queue.name}

security:
  jwt:
    secret: ${JWT_SECRET:12345678}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0
